"""Render the rollout evidence as a standalone HTML artifact."""
import html
import json
from pathlib import Path

root=Path(__file__).resolve().parent/'results'
def read(name):return json.loads((root/name).read_text())
audit=read('archive-audit.json');old=read('legacy-preservation-verified.json');activation=read('activation.json')
recent=read('retrieval-validation-weekly128.json')['summaries'];general=read('general-retrieval-validation.json')['summary']
selected={r['scope']:r for r in recent}
for r in general:
    name=r['config'];scope=name.split('_ef')[0]
    if name.endswith('_ef256_k500') or (name.endswith('_ef1000_k500') and activation['general_ef']==1000) or (name.endswith('_ef256_k200') and activation['general_ef']==256):selected[scope]=r
rows=[]
labels={'7d':'7 days','30d':'30 days','90d':'3 months','180d':'6 months','365d':'1 year','all':'All time'}
for scope,label in labels.items():
    for field in ['', '_field']:
        r=selected[scope+field];rows.append(f'<tr><td>{label}</td><td>{"cs.LG" if field else "None"}</td><td>{100*r["recall"]:.2f}%</td><td>{r["median_ms"]:.2f} ms</td><td>{r["p95_ms"]:.2f} ms</td></tr>')
paths=[('New full-precision originals','/home/arxiv/arxiv_troller/data/voyage4/shards/'),('Preserved pilot originals','/home/arxiv/arxiv_troller/experiments/voyage4-pilot-20260919/data/'),('Paper IDs, input snapshots and version lookup','/home/arxiv/arxiv_troller/data/voyage4/catalog.sqlite3'),('Independent backup of legacy embedding tables','/home/arxiv/arxiv_troller/data/voyage4/backups/pre-voyage4-embeddings.dump')]
path_rows=''.join(f'<dt>{html.escape(label)}</dt><dd><code>{html.escape(path)}</code></dd>' for label,path in paths)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>arXiv Troller · Voyage 4 rollout</title>
<style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#202b3c;background:#f4f6fa}body{max-width:1100px;margin:auto;padding:36px 24px 70px}h1{font-size:38px;letter-spacing:-1.3px;margin:10px 0}h2{font-size:23px;margin:0 0 14px}p{line-height:1.65;max-width:900px}.kicker{color:#476082;font-weight:650;letter-spacing:.12em;font-size:12px;text-transform:uppercase}.badge{display:inline-block;padding:6px 12px;border-radius:30px;background:#dff3e8;color:#12623a;font-size:13px;font-weight:700}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:26px 0}.card,section{background:white;border:1px solid #dfe5ef;border-radius:14px;padding:24px}.big{font-size:30px;font-weight:720;letter-spacing:-1px}.small{font-size:13px;color:#596981;margin-top:8px}section{margin-top:22px}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e9edf3;white-space:nowrap}th{color:#5b6a80;font-weight:600}td:nth-child(n+3){font-variant-numeric:tabular-nums}code{font-size:12px;overflow-wrap:anywhere}dt{font-weight:600;margin-top:16px}dd{margin:6px 0 0;color:#58677d}.note{background:#edf3fd;padding:16px 20px;border-radius:10px;font-size:14px}.foot{font-size:12px;color:#65768d;margin-top:22px}a{color:#2359a8}@media(max-width:720px){.cards{grid-template-columns:1fr}h1{font-size:30px}body{padding:24px 14px}section{padding:18px}}
</style>
<div class="kicker">arXiv Troller · Oracle VM</div><h1>Voyage 4 Large is live</h1><span class="badge">Originals preserved · integrity checks passed</span>
<p>The complete paper archive is embedded through the standard API. Monthly retrieval uses a maintained 2048-dimensional HNSW index, with full-float32 rescoring. The old retrieval backend and all old embeddings remain available.</p>
<div class="cards"><div class="card"><div class="big">{COUNT}</div><div class="small">papers with saved embeddings</div></div><div class="card"><div class="big">2048 · float32</div><div class="small">original API dimensions and precision retained</div></div><div class="card"><div class="big">{MONTH} ms</div><div class="small">monthly median SQL latency · {RECALL}% recall</div></div></div>
<section><h2>What changed</h2><p>The rolling table covers the latest 30 days plus a one-day maintenance buffer. Every search still applies its exact date restriction. New papers and revised abstracts enter an hourly queue; saved originals are imported before the search copies are updated. Expiry removes only rows from the rolling cache. There is no scheduled index rebuild.</p><p>Monthly searches use ef=128; field-filtered rolling searches use ef=512 and rescore at least 50 candidates against original float32 vectors. Older unfiltered searches use the permanent binary index, then full-dimensional cosine rescoring. Older field-filtered searches score all eligible binary vectors before rescoring 500 candidates.</p><div class="note">Full-precision originals are immutable files. PostgreSQL's general half-precision vectors and binary vectors are derived search copies; they do not replace the originals. Previous abstract versions are retained.</div></section>
<section><h2>Measured retrieval</h2><p>Recall@20 against exhaustive cosine on original float32 values, calculated with float64 arithmetic. These measurements use the complete archive, including all-time candidates. Recent windows use the original 36 benchmark sources; older windows use a stratified subset of 12. Latencies measure warm SQL execution and fetch, excluding application rendering and source-file lookup.</p><div class="scroll"><table><thead><tr><th>Window</th><th>Field</th><th>Recall@20</th><th>Median</th><th>p95</th></tr></thead><tbody>{ROWS}</tbody></table></div><p class="small">Small query samples do not guarantee future recall. Index maintenance was tested across expiry, metadata changes, abstract revisions and reversions; long-term performance still requires monitoring.</p></section>
<section><h2>Preservation and verification</h2><p>All {SHARDS} archived files passed checksum, shape, precision and model checks. Every current paper has both a saved original and a database search copy. The original embedding tables passed a byte-level comparison against their pre-rollout baseline. Their separate database backup remains saved.</p><dl>{PATHS}</dl><p class="small">These originals and backups reside on the VM; this rollout does not create an off-VM disaster-recovery copy.</p></section>
<section><h2>Usage and capacity</h2><p>New generation processed <strong>{TOKENS} tokens</strong>, in addition to the preserved pilot. Its list-price equivalent is <strong>${COST}</strong>; this is not a confirmed invoice amount and does not deduct account credits. The VM has approximately <strong>{FREE} GiB free</strong> after the rollout.</p><p>Hourly maintenance is enabled. Django checks, real query execution, field filtering, pagination and existing-tag retrieval passed. Production traffic was checked after the application reloaded.</p></section>
<p class="foot">Activated {WHEN}. Reverting retrieval only requires disabling VOYAGE4_ENABLED and reloading the app; neither embedding archive needs to be deleted.</p></html>'''
values={'COUNT':f'{audit["current_papers"]:,}','MONTH':f'{selected["30d"]["median_ms"]:.2f}','RECALL':f'{100*selected["30d"]["recall"]:.2f}',
'ROWS':''.join(rows),'SHARDS':f'{audit["shards"]:,}','PATHS':path_rows,'TOKENS':f'{audit["new_response_tokens"]:,}','COST':f'{audit["new_list_price_usd"]:.2f}','FREE':f'{activation["free_bytes"]/2**30:.1f}','WHEN':html.escape(activation['activated_utc'])}
for key,value in values.items():page=page.replace('{'+key+'}',value)
(root/'rollout.html').write_text(page)
