# Generated by Django 5.2.6 on 2025-09-24 04:44

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='vector_new',
            field=pgvector.django.VectorField(dimensions=3072, null=True),
        ),
    ]
