# Generated by Django 5.2.6 on 2025-09-24 04:58

from django.db import migrations, connection


def populate_vectors(apps, schema_editor):
    with connection.cursor() as cursor:
        # Get count for progress
        cursor.execute("""
            SELECT COUNT(*) FROM papers_embedding 
            WHERE vector_new IS NULL AND vector IS NOT NULL
        """)
        total = cursor.fetchone()[0]
        print(f"Total embeddings to process: {total}")
        
        if total == 0:
            print("No embeddings to process")
            return
        
        # Direct SQL update - converts JSON to vector format
        print("Starting bulk SQL update...")
        cursor.execute("""
            UPDATE papers_embedding 
            SET vector_new = vector::text::vector
            WHERE vector_new IS NULL AND vector IS NOT NULL
        """)
        
        print(f"Updated {cursor.rowcount} rows")

def reverse_populate(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE papers_embedding SET vector_new = NULL")
class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_add_vector_field_to_embedding"),
    ]

    operations = [
        migrations.RunPython(populate_vectors, reverse_populate),
    ]
