# Generated by Django 5.2.6 on 2025-09-24 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0003_populate_vector_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='vector',
        ),
        migrations.RenameField(
            model_name='embedding',
            old_name='vector_new',
            new_name='vector',
        ),
    ]
