# Generated by Django 5.2.6 on 2025-09-25 04:32

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0004_remove_old_vector_field"),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='vector_halfvec',
            field=pgvector.django.HalfVectorField(dimensions=3072, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE papers_embedding SET vector_halfvec = vector::halfvec(3072);",
            reverse_sql="UPDATE papers_embedding SET vector_halfvec = NULL;"
        ),
    ]
