# Generated by Django 5.2.6 on 2025-09-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0006_add_hnsw_vector_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='vector',
        ),
        migrations.RenameField(
            model_name='embedding',
            old_name='vector_halfvec',
            new_name='vector',
        ),
    ]
