# Generated by Django 5.2.6 on 2025-10-04 17:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ("papers", "0009_user_removedpaper_tag_taggedpaper_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_papers_created ON papers_paper(created);",
            reverse_sql="DROP INDEX IF EXISTS idx_papers_created;",
        ),
    ]
