# Generated by Django 5.2.6 on 2025-10-10 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0011_alter_removedpaper_unique_together_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
                "CREATE INDEX papers_paper_title_trgm_idx ON papers_paper USING GIN (title gin_trgm_ops);",
            ],
            reverse_sql="DROP INDEX papers_paper_title_trgm_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX papers_paper_categories_gin_idx ON papers_paper USING GIN(categories);",
            reverse_sql="DROP INDEX papers_paper_categories_gin_idx;",
        ),
    ]
