# Generated by Django 5.2.6 on 2025-10-28 02:21

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0012_title_cat_indices"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingReduced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("embedding_type", models.CharField(max_length=50)),
                (
                    "vector",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=3072, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "papers_embedding_reduced",
            },
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("keyname", "forenames"),
                name="papers_author_keyname_forenames_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddField(
            model_name="embeddingreduced",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddingreduced",
            index=models.Index(
                fields=["model_name", "embedding_type"],
                name="papers_embe_model_n_ad2162_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="embeddingreduced",
            unique_together={("paper", "model_name", "embedding_type")},
        ),
    ]
