# Generated by Django 5.2.6 on 2025-10-28 02:22

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0013_embeddingreduced_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingVoyageBit2048",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", pgvector.django.halfvec.HalfVectorField(dimensions=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddingVoyageHalf2048",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", pgvector.django.halfvec.HalfVectorField(dimensions=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddingVoyageHalf256",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", pgvector.django.halfvec.HalfVectorField(dimensions=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
                    ),
                ),
            ],
        ),
    ]
