# Generated by Django 5.2.6 on 2025-10-28 02:26

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0014_embeddingvoyagebit2048_embeddingvoyagehalf2048_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingGeminiHalf512",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vector",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=3072, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EmbeddingReduced",
        ),
    ]
