# Generated by Django 5.2.6 on 2025-10-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0015_embeddinggeminihalf512_delete_embeddingreduced"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Embedding",
            new_name="EmbeddingGeminiHalf3072",
        ),
        migrations.RenameIndex(
            model_name="embeddinggeminihalf3072",
            new_name="papers_embe_model_n_4435d9_idx",
            old_name="papers_embe_model_n_dcbb1f_idx",
        ),
    ]
