# Generated by Django 5.2.6 on 2025-10-28 02:38

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0016_rename_embedding_embeddinggeminihalf3072_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="embeddinggeminihalf3072",
            name="papers_embe_model_n_4435d9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="embeddinggeminihalf3072",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="embeddinggeminihalf3072",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
            ),
        ),
        migrations.AlterField(
            model_name="embeddinggeminihalf3072",
            name="vector",
            field=pgvector.django.halfvec.HalfVectorField(default=0, dimensions=3072),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="embeddinggeminihalf3072",
            name="embedding_type",
        ),
        migrations.RemoveField(
            model_name="embeddinggeminihalf3072",
            name="model_name",
        ),
    ]
