# Generated by Django 5.2.6 on 2025-10-28 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "papers",
            "0017_remove_embeddinggeminihalf3072_papers_embe_model_n_4435d9_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embeddinggeminihalf3072",
            name="id",
        ),
        migrations.AlterField(
            model_name="embeddinggeminihalf3072",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="papers.paper",
            ),
        ),
    ]
