# Generated by Django 5.2.6 on 2025-10-28 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0018_remove_embeddinggeminihalf3072_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embeddinggeminihalf512",
            name="id",
        ),
        migrations.RemoveField(
            model_name="embeddingvoyagebit2048",
            name="id",
        ),
        migrations.RemoveField(
            model_name="embeddingvoyagehalf2048",
            name="id",
        ),
        migrations.RemoveField(
            model_name="embeddingvoyagehalf256",
            name="id",
        ),
        migrations.AlterField(
            model_name="embeddinggeminihalf512",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="papers.paper",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingvoyagebit2048",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="papers.paper",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingvoyagehalf2048",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="papers.paper",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingvoyagehalf256",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="papers.paper",
            ),
        ),
    ]
