# Generated by Django 5.2.6 on 2025-10-28 03:11

import pgvector.django.bit
import pgvector.django.halfvec
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0019_remove_embeddinggeminihalf512_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddinggeminihalf512",
            name="vector",
            field=pgvector.django.halfvec.HalfVectorField(dimensions=512),
        ),
        migrations.RemoveField(
            model_name="embeddingvoyagebit2048",
            name="vector",
        ),
        migrations.AddField(
            model_name="embeddingvoyagebit2048",
            name="vector",
            field=pgvector.django.bit.BitField(length=2048),
        ),
    ]
