# Generated by Django 5.2.6 on 2025-09-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0005_change_vec_to_half"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX papers_embedding_vector_hnsw_idx 
            ON papers_embedding 
            USING hnsw (vector_halfvec halfvec_l2_ops)
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="DROP INDEX IF EXISTS papers_embedding_vector_hnsw_idx;"
        ),
    ]
