# Generated by Django 5.2.6 on 2025-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0007_finalize_halfvec_migration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["-created"], name="papers_paper_created_idx"),
        ),
    ]
