# Generated by Django 5.2.6 on 2025-09-29 03:05

import django.db.models.deletion
import pgvector.django.halfvec
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0008_add_paper_created_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RemovedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaggedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="paper",
            name="papers_paper_created_idx",
        ),
        migrations.AlterField(
            model_name="embedding",
            name="vector",
            field=pgvector.django.halfvec.HalfVectorField(
                blank=True, dimensions=3072, null=True
            ),
        ),
        migrations.AddField(
            model_name="removedpaper",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="removedpaper",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="removed_papers",
                to="papers.tag",
            ),
        ),
        migrations.AddField(
            model_name="taggedpaper",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
            ),
        ),
        migrations.AddField(
            model_name="taggedpaper",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_papers",
                to="papers.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="removedpaper",
            unique_together={("tag", "paper")},
        ),
        migrations.AlterUniqueTogether(
            name="taggedpaper",
            unique_together={("tag", "paper")},
        ),
    ]
