# Generated by Django 5.2.6 on 2025-10-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0010_add_created_index"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="removedpaper",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="removedpaper",
            name="paper",
        ),
        migrations.RemoveField(
            model_name="removedpaper",
            name="tag",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX papers_author_keyname_forenames_idx 
                ON papers_author (keyname, forenames) 
                NULLS NOT DISTINCT;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS papers_author_keyname_forenames_idx;
            """,
        ),
        migrations.DeleteModel(
            name="RemovedPaper",
        ),
    ]
